numbers: numbers.c
	gcc -o numbers.o numbers.c
prime: primes.c
	gcc -o primes.o primes.c
testNum: numbers
	./numbers.o
testPrimes: primes
	./primes.o
pipe: numbers prime
	./numbers.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o | ./primes.o
